#:kivy 2.1.0

<VirtualKeyboard>:
#:kivy 2.1.0

<VirtualKeyboard>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: "background.jpg"
    ButtonSet:
        anchor_x: "center"
        anchor_y: "bottom"
        pos_hint: {'center_x': 0.51, 'top': 0.96}
        Button:
            id: one
            pos_hint: {'center_x': 0.05, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "1"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: two
            pos_hint: {'center_x': 0.13, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "2"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: three
            pos_hint: {'center_x': 0.21, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "3"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: four
            pos_hint: {'center_x': 0.29, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "4"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: five
            pos_hint: {'center_x': 0.37, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "5"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: six
            pos_hint: {'center_x': 0.45, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "6"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: seven
            pos_hint: {'center_x': 0.53, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "7"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: eight
            pos_hint: {'center_x': 0.61, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "8"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            on_press: app.callback(self)
            id: nine
            pos_hint: {'center_x': 0.69, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "9"
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: zero
            pos_hint: {'center_x': 0.77, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "0"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            on_press: app.callback(self)
            id: parenthesis
            pos_hint: {'center_x': 0.85, 'top': 1}
            size_hint:( 0.087, 0.150)
            text: "()"
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            on_press: app.callback(self)
            id: plus
            pos_hint: {'center_x': 0.93, 'top':1}
            size_hint:( 0.087, 0.150)
            text: "+"
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            on_press: app.callback(self)
            id: minus
            pos_hint: {'center_x': 0.93, 'top':0.85}
            size_hint:( 0.087, 0.150)
            text: "-"
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: q
            pos_hint: {'center_x': 0.05, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "q"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: w
            pos_hint: {'center_x': 0.13, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "w"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: e
            pos_hint: {'center_x': 0.21, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "e"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: r
            pos_hint: {'center_x': 0.29, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "r"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: t
            pos_hint: {'center_x': 0.37, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "t"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: y
            pos_hint: {'center_x': 0.45, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "y"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: u
            pos_hint: {'center_x': 0.53, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "u"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: i
            pos_hint: {'center_x': 0.61, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "i"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: o
            pos_hint: {'center_x': 0.69, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "o"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: p
            pos_hint: {'center_x': 0.77, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "p"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: keys
            pos_hint: {'center_x': 0.85, 'top': 0.85}
            size_hint: (0.087, 0.150)
            text: "{}"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: a
            pos_hint: {'center_x': 0.21, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "a"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: s
            pos_hint: {'center_x': 0.29, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "s"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: d
            pos_hint: {'center_x': 0.37, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "d"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: f
            pos_hint: {'center_x': 0.45, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "f"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: g
            pos_hint: {'center_x': 0.53, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "g"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: h
            pos_hint: {'center_x': 0.61, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "h"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: j
            pos_hint: {'center_x': 0.69, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "j"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: k
            pos_hint: {'center_x': 0.77, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "k"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: l
            pos_hint: {'center_x': 0.85, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "l"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: z
            pos_hint: {'center_x': 0.21, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: "z"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: x
            pos_hint: {'center_x': 0.29, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: "x"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: c
            pos_hint: {'center_x': 0.37, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: "c"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: v
            pos_hint: {'center_x': 0.45, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: "v"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: b
            pos_hint: {'center_x': 0.53, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: "b"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: n
            pos_hint: {'center_x': 0.61, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: "n"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: m
            pos_hint: {'center_x': 0.69, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: "m"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: comma
            pos_hint: {'center_x': 0.77, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: ","
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: dot
            pos_hint: {'center_x': 0.85, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: "."
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: two_dots
            pos_hint: {'center_x': 0.93, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: ":"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: dot_comma
            pos_hint: {'center_x': 0.93, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: ";"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)

        Button:
            id: special1
            pos_hint: {'center_x': 0.05, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "^"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: special2
            pos_hint: {'center_x': 0.93, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "ç"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: special3
            pos_hint: {'center_x': 0.13, 'top': 0.70}
            size_hint: (0.087, 0.150)
            text: "\\"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: special4
            pos_hint: {'center_x': 0.05, 'top': 0.40}
            size_hint: (0.087, 0.150)
            text: "@"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: special4
            pos_hint: {'center_x': 0.05, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: "?"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: special4
            pos_hint: {'center_x': 0.13, 'top': 0.55}
            size_hint: (0.087, 0.150)
            text: "/"
            on_press: app.callback(self)
            color: 0,0,0,1
            background_normal: 'Button.png'
            background_color: (1, 1, 1, 1)
        Button:
            id: end
            pos_hint: {'center_x': 0.05, 'top': 0.25}
            size_hint: (0.087, 0.150)
            on_press: app.end(self)
            color: 0,0,0,1
            background_normal: ''
            background_color: 0,0,0,0
            Image:
                source: 'CloseButton.png'
                background_normal: ''
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                y: self.parent.y
                x: self.parent.x
                size: self.parent.size
                allow_stretch: True
        Button:
            id: minimize
            pos_hint: {'center_x': 0.13, 'top': 0.25}
            size_hint: (0.087, 0.150)
            on_press: app.minimize(self)
            color: 0,0,0,1
            background_normal: ''
            background_color: 0,0,0,0
            Image:
                source: 'MinimizeButton.png'
                background_normal: ''
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                y: self.parent.y
                x: self.parent.x
                size: self.parent.size
                allow_stretch: True


